### ISSUE TITLE
iOS: version conflict with Firebase libs

### ISSUE THREAD

**Issue by hnvn** [juliansteenbakker/mobile_scanner#335]
The current version of this lib is conflicted with the latest version of Firebase libs, here's log:
```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_storage (from `.symlinks/plugins/firebase_storage/ios`) was resolved to 11.0.1, which depends on
      Firebase/Storage (= 10.0.0) was resolved to 10.0.0, which depends on
        FirebaseStorage (~> 10.0.0) was resolved to 10.0.0, which depends on
          GTMSessionFetcher/Core (~> 2.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 2.6.0) was resolved to 2.6.0, which depends on
        MLKitBarcodeScanning (~> 1.7.0) was resolved to 1.7.0, which depends on
          MLKitVision (~> 3.0) was resolved to 3.0.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)
```

**Comment by oerni74** [comment]
```
pod repo update
pod update GTMSessionFetcher/Core
```
solved it for me.

**Comment by peukerjonathan** [comment]
> ```
> pod repo update
> pod update GTMSessionFetcher/Core
> ```
> 
> solved it for me. However, the problem for me was firebase_auth not firebase_storage.

If this does not work try:
```
rm -rf ios/Pods
rm ios/Pdofile.lock
flutter clean
pod repo update
```
Then try again.

**Comment by bgetsug** [comment]
From the `pod` output, the issue appears to be with the `Podspec` for `MLKitVision`. Even the latest version (4.2.0) is still locked to `GTMSessionFetcher/Core` 1.1. Since the ML Kit SDK appears to be closed source, I opened a ticket through Google's issue tracker: https://issuetracker.google.com/issues/254418199

**Comment by kyeshmz** [comment]
Nice catch @bgetsug !

**Comment by uzuki-P** [comment]
Is there any workaround on this?
I try both **oerni74** & **peukerjonathan** solution, still no luck

**Comment by PedroTicGal** [comment]
Same issue here, tried @oerni74 and @peukerjonathan solutions but no luck.

**Comment by kekko7072** [comment]
+ 1

**Comment by MagnusJohansson** [comment]
The Google team has assigned the MLKit bug ticket https://issuetracker.google.com/issues/254418199 with a Priority level of P4.
P4 is the lowest priority they are working with, [described as](https://developers.google.com/issue-tracker/concepts/issues#priority):


> P4 | An issue that should be addressed eventually. Such an issue is not relevant to core organizational functions or the work of other teams, or else it relates only to the attractiveness or pleasantness of the system.

All of you who are experiencing this Google bug, could you please browse to the https://issuetracker.google.com/issues/254418199  issue, and click on the "+1" blue button on the top right to make Google aware that it is affecting people.
Thanks.

**Comment by motucraft** [comment]
https://issuetracker.google.com/issues/254418199#comment22

> Currently the next release is planned at the end of Q4.

Will we have to wait a few months for this issue...

**Comment by github-brave** [comment]
Same issue here, any solution?

**Comment by uynguyen** [comment]
+1 Same here ...

**Comment by isairz** [comment]
I roll-backed firebase_storage version, and it works around

- firebase_storage: ^11.0.3
+ firebase_storage: ^10.3.7

**Comment by juliansteenbakker** [comment]
I'm almost done with a new update of this package which will introduce some new functions and update the dependencies as well. With these new dependencies, i did not encounter this error.

**Comment by Theunodb** [comment]
> I'm almost done with a new update of this package which will introduce some new functions and update the dependencies as well. With these new dependencies, i did not encounter this error.

Thank you for the efffort! We are looking forward to the update

**Comment by motoki-osaki** [comment]
> The Google team has assigned the MLKit bug ticket https://issuetracker.google.com/issues/254418199 with a Priority level of P4. P4 is the lowest priority they are working with, [described as](https://developers.google.com/issue-tracker/concepts/issues#priority):
> 
> > P4 | An issue that should be addressed eventually. Such an issue is not relevant to core organizational functions or the work of other teams, or else it relates only to the attractiveness or pleasantness of the system.
> 
> All of you who are experiencing this Google bug, could you please browse to the https://issuetracker.google.com/issues/254418199 issue, and click on the "+1" blue button on the top right to make Google aware that it is affecting people. Thanks.

@MagnusJohansson 
I cannot access the IssueTracker. Why is that?

**Comment by motoki-osaki** [comment]
I don't know why, but Issue Tracker is now accessible.

**Comment by antoninobajeli** [comment]
Helle guys,
I would share with you a possible solution:

1. Create MLKitVision.podspec.json in ios folder taking content from [https://github.com/CocoaPods/Specs/blob/master/Specs/8/1/e/MLKitVision/4.2.0/MLKitVision.podspec.json](https://www.google.com/url?q=https://github.com/CocoaPods/Specs/blob/master/Specs/8/1/e/MLKitVision/4.2.0/MLKitVision.podspec.json&sa=D&source=buganizer&usg=AOvVaw1SvxwhP9ivfDz0zbhf--DU)
2. Create MLKitCommon.podspec.json  in ios folder taking content from [https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json](https://www.google.com/url?q=https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json&sa=D&source=buganizer&usg=AOvVaw05Houqpf5Q1LD2ebCjqYZe)
3. Modify in both files the GTMSessionFetcher/Core definition from 1.1 to version 2.1.

4. Inside your Podfile you have to search for "target 'Runner'" and inside it you have to add the following lines:
```
      pod 'MLKitVision', :podspec => 'MLKitVision.podspec.json'
      pod 'MLKitCommon', :podspec => 'MLKitCommon.podspec.json'
```
5. Run pod install

6. build the app

That solved my issue.

I hope the same to you.

**Comment by psatler** [comment]
I'm facing a similar problem, but between MobileScanner and GoogleMLKitTextRecognition.

```
[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/MLKitCore":
  In Podfile:
    google_mlkit_text_recognition (from `.symlinks/plugins/google_mlkit_text_recognition/ios`) was resolved to 0.5.0, which depends on
      GoogleMLKit/TextRecognition (~> 3.2.0) was resolved to 3.2.0, which depends on
        GoogleMLKit/MLKitCore (= 3.2.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 2.6.0) was resolved to 2.6.0, which depends on
        GoogleMLKit/MLKitCore (= 2.6.0)
```

**Comment by vikt0r40** [comment]
@juliansteenbakker thank you for your effort, does the new version ready or its still in progress?

**Comment by juliansteenbakker** [comment]
It's still in progress. I'm hoping i can release a new beta version this weekend. You can track the progress in #362

**Comment by motucraft** [comment]
I have applied the above workaround and referred to the podfile shared here. It worked for me.
Thanks to those who shared their information.

```yml
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  cloud_firestore_odm: ^1.0.0-dev.40
  firebase_storage: ^11.0.5
  firebase_crashlytics: ^3.0.5
  firebase_messaging: ^14.1.0

  mobile_scanner: ^3.0.0-beta.1
```

<details>
<summary>My Podfile here</summary>

```podspec
# Override Firebase SDK Version
$FirebaseSDKVersion = '10.1.0'
# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # see...
  #   https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1308829103
  #   https://issuetracker.google.com/issues/254418199#comment48
  pod 'MLKitVision', :podspec => 'MLKitVision.podspec.json'
  pod 'MLKitCommon', :podspec => 'MLKitCommon.podspec.json'

  use_frameworks!
  use_modular_headers!

  # see...
  #   https://github.com/firebase/flutterfire/issues/9761#issuecomment-1301997595
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => $FirebaseSDKVersion

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

</details>

**Comment by t-kietzmann** [comment]
I#ve done the same but got this error then with Firebase 10.2.0:

[!] CocoaPods could not find compatible versions for pod "MLKitCommon":
  In Podfile:
    MLKitCommon (from `MLKitCommon.podspec.json`)

    MLKitVision (from `MLKitVision.podspec.json`) was resolved to 4.2.0, which depends on
      MLKitCommon (~> 8.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 2.6.0) was resolved to 2.6.0, which depends on
        GoogleMLKit/MLKitCore (= 2.6.0) was resolved to 2.6.0, which depends on
          MLKitCommon (~> 5.0.0)

**Comment by juliansteenbakker** [comment]
Besides updating the latest beta version, i've also fixed the current stable version with v2.1.0.

This version updates firebase on iOS to the latest version which fixes this issue.

**Comment by motucraft** [comment]
Thanks for releasing v3.0.0-beta.2. I have worked with the following versions without problems.

```yml
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  cloud_firestore_odm: ^1.0.0-dev.41
  firebase_storage: ^11.0.6
  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.1.1
  google_sign_in: ^5.4.2

  mobile_scanner: ^3.0.0-beta.2
```

<details>
<summary>My Podfile (Firebase 10.2.0)</summary>

```podspec
# Override Firebase SDK Version
$FirebaseSDKVersion = '10.2.0'
# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # see...
  #   https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1308829103
  #   https://issuetracker.google.com/issues/254418199#comment48
  pod 'MLKitVision', :podspec => 'MLKitVision.podspec.json'
  pod 'MLKitCommon', :podspec => 'MLKitCommon.podspec.json'

  use_frameworks!
  use_modular_headers!

  # see...
  #   https://github.com/firebase/flutterfire/issues/9761#issuecomment-1301997595
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => $FirebaseSDKVersion

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

</details>

However, removing this workaround will result in an error.

```podspec
  # see...
  #   https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1308829103
  #   https://issuetracker.google.com/issues/254418199#comment48
  pod 'MLKitVision', :podspec => 'MLKitVision.podspec.json'
  pod 'MLKitCommon', :podspec => 'MLKitCommon.podspec.json'
```

```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_storage (from `.symlinks/plugins/firebase_storage/ios`) was resolved to 11.0.6, which depends on
      Firebase/Storage (= 10.2.0) was resolved to 10.2.0, which depends on
        FirebaseStorage (~> 10.2.0) was resolved to 10.2.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    google_sign_in_ios (from `.symlinks/plugins/google_sign_in_ios/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 6.2) was resolved to 6.2.4, which depends on
        GTMSessionFetcher/Core (< 3.0, >= 1.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.0.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitBarcodeScanning (~> 2.2.0) was resolved to 2.2.0, which depends on
          MLKitCommon (~> 8.0) was resolved to 8.0.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)
```

I hope this helps.

**Comment by juliansteenbakker** [comment]
Well in that case it really is a problem with firebase rather than this plugin.

**Comment by motucraft** [comment]
Ultimately, I recognize that this is the fundamental problem.
https://issuetracker.google.com/issues/254418199

**Comment by steven230500** [comment]
> Ultimately, I recognize that this is the fundamental problem. https://issuetracker.google.com/issues/254418199

have you found any solution?

**Comment by motucraft** [comment]
@steven230500 
Workaround. https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1314796725

**Comment by Mayb3Nots** [comment]
Can anyone confirm the workaround works with `10.2.0`. Doesnt seem to work for me.

**Comment by sameer320** [comment]
Please resolve this issue

**Comment by wladosh** [comment]
After all these workarounds I get
`CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In snapshot (Podfile.lock):
    GTMSessionFetcher/Core (< 4.0, = 3.0.0, >= 2.1)

  In Podfile:
    MLKitCommon (from `MLKitCommon.podspec.json`) was resolved to 8.0.0, which depends on
      GTMSessionFetcher/Core (~> 2.1)

Specs satisfying the `GTMSessionFetcher/Core (< 4.0, = 3.0.0, >= 2.1), GTMSessionFetcher/Core (~> 2.1)` dependency were found, but they required a higher minimum deployment target.`

Now, what is the minimum deployment target? I have set it to 15 for testing and it still doesn't work

**Comment by Bamorem** [comment]
> ```ruby
>   # see...
>   #   https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1308829103
>   #   https://issuetracker.google.com/issues/254418199#comment48
>   pod 'MLKitVision', :podspec => 'MLKitVision.podspec.json'
>   pod 'MLKitCommon', :podspec => 'MLKitCommon.podspec.json'
> ```

This works for me but that would be amazing to know when the fix will be apply so that we don't need to use this workaround

**Comment by oakstair** [comment]
Any updates on this? I am stucked from releasing my app as it is now. I will try the fix above when I have some time over.

But I thought that I could wait until this is fixed properly. Have been waiting over two month now ...

**Comment by graphicstone** [comment]
I did this [work-around](https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1314796725) but still getting the issue of No GoogleService-Info.plist found.

```
Looking for  in 
    No GoogleService-Info.plist found. Please ensure it's in the proper directory.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
```

**Comment by edkahara** [comment]
> After all these workarounds I get
> 
> ```
> CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
>   In snapshot (Podfile.lock):
>     GTMSessionFetcher/Core (< 4.0, = 3.0.0, >= 2.1)
> 
>   In Podfile:
>     MLKitCommon (from `MLKitCommon.podspec.json`) was resolved to 8.0.0, which depends on
>       GTMSessionFetcher/Core (~> 2.1)
> 
> Specs satisfying the `GTMSessionFetcher/Core (< 4.0, = 3.0.0, >= 2.1), GTMSessionFetcher/Core (~> 2.1)` dependency were found, but they required a higher minimum deployment target.
> ```
> 
> Now, what is the minimum deployment target? I have set it to 15 for testing and it still doesn't work

@wladosh I've got this exact issue in my project right now. How did you solve it?

**Comment by edkahara** [comment]
> @edkahara I didn't. I just used another scanner library

@wladosh Which one did you use?

**Comment by wladosh** [comment]
@edkahara https://pub.dev/packages/barcode_scan2 this one works for me

**Comment by juliansteenbakker** [comment]
I think this is now fixed in v3.0.0.

**Comment by loic-hamdi** [comment]
> I think this is now fixed in v3.0.0.

Still facing the same issue with v3.0.0

```
cloud_firestore: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
firebase_analytics: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.2.6, which depends on
      Firebase/Auth (= 10.3.0) was resolved to 10.3.0, which depends on
        FirebaseAuth (~> 10.3.0) was resolved to 10.3.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.0.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitBarcodeScanning (~> 2.2.0) was resolved to 2.2.0, which depends on
          MLKitVision (~> 4.2) was resolved to 4.2.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)
```

**Comment by davindermakkar** [comment]
controller.analyzeImage(image.path) fails when an image is chosen from gallery in IOS. Does any faced this using mobile_scanner

**Comment by loic-hamdi** [comment]
> controller.analyzeImage(image.path) fails when an image is chosen from gallery in IOS. Does any faced this using mobile_scanner

This has been in PR  [https://github.com/juliansteenbakker/mobile_scanner/pull/497](https://github.com/juliansteenbakker/mobile_scanner/pull/497) waiting for @juliansteenbakker  to merge it

**Comment by juliansteenbakker** [comment]
Currently the best work around is https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1308829103

Google says that they are planning on fixing this issue somewhere mid march. https://issuetracker.google.com/issues/254418199#comment156

**Comment by davindermakkar** [comment]
Please if you can merge PR #497 @juliansteenbakker.

**Comment by benjameens** [comment]
Still facing the issue ..  I'm using the above highlighted solution  #335

[!] CocoaPods could not find compatible versions for pod "MLKitCommon":
  In Podfile:
    MLKitCommon (from `MLKitCommon.podspec.json`)

    MLKitVision (from `MLKitVision.podspec.json`) was resolved to 4.2.0, which depends on
      MLKitCommon (~> 8.0)

    google_ml_kit (from `.symlinks/plugins/google_ml_kit/ios`) was resolved to 0.6.0, which depends on
      GoogleMLKit/DigitalInkRecognition (~> 2.2.0) was resolved to 2.2.0, which depends on
        MLKitDigitalInkRecognition (~> 1.3.0) was resolved to 1.3.0, which depends on
          MLKitCommon (~> 3.0)
          
 I am using these libraries .If I remove   this package "google_ml_kit"   then its working fine
 
            firebase_messaging: ^14.1.0
            firebase_core: ^2.2.0
            firebase_auth: ^4.1.2
            google_ml_kit: ^0.7.2

**Comment by davindermakkar** [comment]
@juliansteenbakker I am using image picker also. The AnalyseImage method returns true. Can you please explain how to get the barcode values?

**Comment by Abhi011999** [comment]
Those who are facing errors with other `MLKit` podspecs, i have added a comment here - https://issuetracker.google.com/issues/254418199#comment165

**Comment by davindermakkar** [comment]
PLease if someone can help on how to retrieve barcode values from a picture in mobile scanner.

**Comment by collamaf** [comment]
> Those who are facing errors with other `MLKit` podspecs, i have added a comment here - https://issuetracker.google.com/issues/254418199#comment165

Hello. Any update on this? Following this link I see that `FirebaseCore 10.7.0` should be now available, but in my case it does not seem to fix the pod install problem with `Mobile Scanner`.
Should I do some particular procedure to update it?
Thanks

**Comment by ritikjainx** [comment]
Can we please update the dependency "GoogleMLKit/BarcodeScanning" to 4.0.0 in mobile_scanner.podspec as it solves the issue of resolving ios pod with latest firebase version @juliansteenbakker  !

**Comment by juliansteenbakker** [comment]
Thanks for the headsup! Before publishing on pub.dev, can anyone verify that this will fix the issue?

I have updated the code on the master branch. Please try it out with:
```dart
  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner
      ref: master
```

The following things has changed in this release:

Improvements:
[iOS] Updated GoogleMLKit/BarcodeScanning to 4.0.0
[Android] Updated com.google.mlkit:barcode-scanning from 17.0.3 to 17.1.0

Bugs fixed:
Fixed onDetect not working with analyzeImage
[iOS] explicit returned type for compactMap

**Comment by juliansteenbakker** [comment]
Thanks for testing! I have released v3.2.0.

**Comment by oakstair** [comment]
Hum .. don't know if it is related by I now get

[!] CocoaPods could not find compatible versions for pod "MLKitVision":
  In Podfile:
    MLKitVision (from `MLKitVision.podspec.json`)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.2.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 4.0.0) was resolved to 4.0.0, which depends on
        MLKitBarcodeScanning (~> 3.0.0) was resolved to 3.0.0, which depends on
          MLKitVision (~> 5.0)

**Comment by PlayCulture** [comment]
I've been facing a similar issue with pods and mobile_scanner (v3.3.0).

`[!] CocoaPods could not find compatible versions for pod "mobile_scanner"`

and also

`[!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified`

For context I'm working on Windows and using CodeMagic to build for Android and iOS, so no direct access to Xcode/etc.

The solution was to edit the following file: 

**(Project Root)**/ios/Runner.xcodeproj/project.pbxproj 

and set all instances of IPHONEOS_DEPLOYMENT_TARGET to match the version shown in:

**(Flutter Plugins)**/mobile_scanner-3.3.0/ios/mobile_scanner.podspec

which looks like

`s.platform = :ios, '11.0'`

Hope that helps someone!

**Comment by BilalAhmed-1998** [comment]
I was using the old solution: 
Hello everyone,
a temporary solution I found is the following:

1- Create MLKitVision.podspec.json in ios folder taking content from [https://github.com/CocoaPods/Specs/blob/master/Specs/8/1/e/MLKitVision/4.2.0/MLKitVision.podspec.json](https://www.google.com/url?q=https://github.com/CocoaPods/Specs/blob/master/Specs/8/1/e/MLKitVision/4.2.0/MLKitVision.podspec.json&sa=D&source=buganizer&usg=AOvVaw1SvxwhP9ivfDz0zbhf--DU)
2- Create MLKitCommon.podspec.json  in ios folder taking content from [https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json](https://www.google.com/url?q=https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json&sa=D&source=buganizer&usg=AOvVaw05Houqpf5Q1LD2ebCjqYZe)
3- Modify in both files the GTMSessionFetcher/Core definition from 1.1 to version 2.1.

4- Inside your Podfile you have to search for "target 'Runner'" and insite it you have to add the following lines:
      pod 'MLKitVision', :podspec => 'MLKitVision.podspec.json'
      pod 'MLKitCommon', :podspec => 'MLKitCommon.podspec.json'
 

5- Run pod install

6- build the app

//////////--------------------------//////////

But when I updated my mobile scanner to 3.4.1^ , it is showing the following errors:


CocoaPods could not find compatible versions for pod "MLKitCommon":
  In Podfile:
    MLKitCommon (from `MLKitCommon.podspec.json`)

    MLKitVision (from `MLKitVision.podspec.json`) was resolved to 4.2.0, which depends on
      MLKitCommon (~> 8.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.2.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 4.0.0) was resolved to 4.0.0, which depends on
        GoogleMLKit/MLKitCore (= 4.0.0) was resolved to 4.0.0, which depends on
          MLKitCommon (~> 9.0.0)



Do i need to change something in old solution?

**Comment by yavuzfeti** [comment]
> > ```
> > pod repo update
> > pod update GTMSessionFetcher/Core
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > solved it for me. However, the problem for me was firebase_auth not firebase_storage.
> 
> If this does not work try:
> 
> ```
> rm -rf ios/Pods
> rm ios/Pdofile.lock
> flutter clean
> pod repo update
> ```
> 
> Then try again.

*rm ios/Pdofile.lock
