### ISSUE TITLE
Samsung Galaxy A23 wrong scan area

### ISSUE THREAD

**Issue by p3pp8** [juliansteenbakker/mobile_scanner#604]
- Mobile scanner 3.2.0 
- Device Samsung Galaxy A23 (tested about 4 device with same result)

It seems that the detection area is located at the upper right screen edge and that it is very small, infact to detect codes i have to put the camera backward enough to reduce the framed code size and move it to the upper right screen edge. 

[InkedScreenshot_20230422_095609_DropPay Stage](https://user-images.githubusercontent.com/1229340/233771212-d268d0f4-fa9b-44ee-8836-bf642b753490.jpg)

**Comment by p3pp8** [comment]
Just tested using the scanWindow attribute but seems to be ignored.

**Comment by p3pp8** [comment]
Fixed uncommenting this line in MobileScanner.kt inside method start():

```
analysisBuilder.setTargetResolution(Size(1440, 1920))
```

I've tried out many resolutions and it always do the job, so i guess, for certain devices, target resolution for analysis builder must be set.

**Comment by p3pp8** [comment]
This one solves the problem without any aspect ratio issue, no need to set target resolution anymore:

```
            val camProfile = CamcorderProfile.get(CamcorderProfile.QUALITY_1080P)
            analysisBuilder.setDefaultResolution(Size(camProfile.videoFrameWidth,
                camProfile.videoFrameHeight))
```

I don't know if this is the right solution but in my case i've tested many devices and everything seems working as aspected.

**Comment by danielleung30** [comment]
Did you tested on ios device?

**Comment by danielleung30** [comment]
Thank you bro, you save the day

**Comment by rpelant** [comment]
Hello,
any news on this? When this issue will be resolved? Having the same symptoms reading QR code on A23.

**Comment by juliansteenbakker** [comment]
I am working on an updated version of #612 which should fix this issue

**Comment by nirbar89** [comment]
Any one test version 3.5.1

**Comment by WelliRigo** [comment]
Tested on 4.0.0 and the issue is still there

**Comment by rpelant** [comment]
Issue is easily resolved setting cameraResolution in MobileScannerController to  some reasonable value , for example 1024, 768

**Comment by WelliRigo** [comment]
Yes, but... still an issue. Also setting the resolution has other implications

**Comment by burekas7** [comment]
Hi,
Any update here?

**Comment by p3pp8** [comment]
The author of this plugin already managed to solve this issue, just set a 4:3 cameraResolution when constructing MobileScannerController. 

```
    final _scannerController = MobileScannerController(
      // 24MPix with an aspect of 4:3 
      cameraResolution: const Size(6080, 8096),
    );
```

Feel free to set a higher resolution, if not available it will be set using the nearest one.

Hope this will be useful!

**Comment by lokalathlet** [comment]
Hi @p3pp8, I am facing the same issue in production with Samsung A23 devices. Do you use this code in your production app, and does this solution have no side effects on other devices with different camera aspects? Any onformation would be greatly appreciated.

**Comment by p3pp8** [comment]
@lokalathlet yes, i'm using it in production app without any problem!

cheers
