### ISSUE TITLE
 Another exception was thrown: PlatformException(error, No active stream to cancel, null, null)

### ISSUE THREAD

**Issue by gslovemy** [juliansteenbakker/mobile_scanner#636]
[        ] Reloaded 31 of 2804 libraries in 1,298ms (compile: 607 ms, reload: 497 ms, reassemble: 103 ms).
[+3221 ms]
                    ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following PlatformException was thrown while de-activating platform stream on channel
                    dev.steenbakker.mobile_scanner/scanner/event:
                    PlatformException(error, No active stream to cancel, null, null)

                    When the exception was thrown, this was the stack:
                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
                    <asynchronous suspension>
                    #2      EventChannel.receiveBroadcastStream.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:649:9)
                    <asynchronous suspension>
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[+4200 ms]
                    Another exception was thrown: PlatformException(error, No active stream to cancel, null, null)

Flutter version 3.3.9
moblie_scan 3.2.0

**Comment by tologonkudaiberdiuulu** [comment]
Any progress on this issue?

**Comment by varsik-eucalyptus** [comment]
I am gearing the same issue. Any progress on this?

**Comment by emrahkenan** [comment]
I am having the same issue.

flutter version: 3.10.5
mobile scanner: 3.2.0



firebase crash event

```
flutter_error_exception	PlatformException(error, No active stream to cancel, null, null)
flutter_error_reason	thrown while de-activating platform stream on channel dev.steenbakker.mobile_scanner/scanner/event
```

Stack trace
```
	Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference
       at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:2172)
       at android.hardware.camera2.legacy.CameraDeviceUserShim$CameraCallbackThread$CallbackHandler.handleMessage(CameraDeviceUserShim.java:327)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by cody1024d** [comment]
I'm seeing this issue as well. I'd like to also include some further research I did, that may help provide more context.

The exception that @emrahkenan posted:
[Google Issue That Describes Same Exception](https://issuetracker.google.com/issues/236055506#comment13)

The google dev here specifically recommends:
> When invoking SurfaceRequest.provideSurface(surface, executor,  Consumer<Result>) ,  the Consumer will get notified that the surface is safe to be released.  

Could it be that we're not releasing the surface (or the underlying texture) at the right time?

Either way I think some additional logging within that callback may help further debug this issue, as there are several results that may be provided, which further describe any errors that occur when binding the surface to the request.

(provideSurface result constants)[https://developer.android.com/reference/androidx/camera/core/SurfaceRequest.Result#constants_1]

**Comment by michael-joseph-payne** [comment]
same issue....completely screws up repeat scans

**Comment by ozkayas** [comment]
Any news?
Having same issue with mobile_scanner: 3.5.5
Is this fixed with the latest version 5.0.0 ??

**Comment by lberaldodev** [comment]
@ozkayas the latest version did fix for you ?

**Comment by juliansteenbakker** [comment]
I'm closing this as there is no activity, and newer versions of this plug are already released. If this still happens with the latest version let me know by commenting.

**Comment by cybrox** [comment]
Just as a heads-up, this ~~is~~ was still happening for us in production right now using `mobile_scanner` version `7.0.1`.

After some investigation, this was caused by a stream listener not being cancelled properly and `controller.start()` or `controller.stop()` being called on a disposed `MobileScannerController`.

In my experiments, the error mentioned in this issue was always preceded by:
```
MobileScannerException (MobileScannerException(controllerDisposed, The MobileScannerController was used after it was disposed.))
```

For reference, this is our QR-Code scanner wrapper widget including the fix:

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

class QrCodeWidget extends StatefulWidget {
  final Function(String)? onCodeFound;
  final Stream<void>? flipCamera;
  final Stream<void>? pauseCamera;
  final Stream<void>? resumeCamera;

  const QrCodeWidget({
    Key? key,
    this.onCodeFound,
    this.flipCamera,
    this.pauseCamera,
    this.resumeCamera,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => _QrCodeWidgetState();
}

class _QrCodeWidgetState extends State<QrCodeWidget> {
  /// The controller used by the scanner library
  final controller = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
  );

  /// Subscriptions to streams from parent element
  StreamSubscription? flipCameraSubscription;
  StreamSubscription? pauseCameraSubscription;
  StreamSubscription? resumeCameraSubscription;

  @override
  void initState() {
    super.initState();

    this.flipCameraSubscription = this.widget.flipCamera?.listen((event) {
      controller.switchCamera();
    });

    // FIX: This assignment was missing and the stream handler was never cancelled!
    this.pauseCameraSubscription = widget.pauseCamera?.listen((event) {
      controller.stop();
    });

    // FIX: This assignment was missing and the stream handler was never cancelled!
    this.resumeCameraSubscription = widget.resumeCamera?.listen((event) {
      controller.start();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Expanded(
          flex: 2,
          child: MobileScanner(
            controller: controller,
            onDetect: (BarcodeCapture capture) {
              if (capture.barcodes.isEmpty) return;
              final barcode = capture.barcodes[0];

              if (barcode.format != BarcodeFormat.qrCode) return;
              if (barcode.rawValue == null) return;
              controller.stop();

              this.widget.onCodeFound?.call(barcode.rawValue!);
            },
          ),
        ),
      ],
    );
  }

  // In order to get hot reload to work we need to pause the camera if the
  // platform is android, or resume the camera if the platform is iOS.
  @override
  void reassemble() {
    super.reassemble();

    this.controller.stop();
    this.controller.start();
  }

  @override
  void dispose() {
    controller.stop();
    controller.dispose();

    flipCameraSubscription?.cancel();
    pauseCameraSubscription?.cancel();
    resumeCameraSubscription?.cancel();

    super.dispose();
  }
}
```

Obviously, this is not a drop-in fix for anyone else using this library, this code is just provided for context to see what we did wrong to run into this error.

**Comment by JLi1111** [comment]
@cybrox Thank you for your investigation. It's really helpful to me. 
I solved the dispose issue using this method.
```dart
void _stopCamera() async {
    await _barcodeSubscription?.cancel();
    await _controller?.dispose();
    _controller = null;
}
```

**Comment by usherwaltz** [comment]
We're still getting this issue on latest package / flutter.

PlatformException(error, No active stream to cancel, null, null)

flutter: 3.47.2
mobile_scanner: 7.4.2

Interesting is that it's only happening on Samsung Galaxy devices for us.
